[metadata]
name = amlro-gui
version = 0.1.0
description = Active Machine Learning Reaction Optimizer GUI
author = Dulitha Prasanna Kulathunga
license = MIT
platforms = any

[options]
packages = find:
include_package_data = True
zip_safe = False
python_requires = >=3.8
install_requires =
    flask
    pandas
    numpy
    scikit-learn
    AMLRO @ git+https://github.com/RxnRover/amlro.git

[options.package_data]
amlro_gui =
    static/*/*
    templates/*.html

[options.entry_points]
console_scripts =
    amlro-app = amlro_gui.run:run
